from enum import IntEnum
class Op(IntEnum):
    NOP=0; TURN_L=1; TURN_R=2; MOVE=3; SENSE=4; EAT=5; STORE=6; DIVIDE=7; EDIT=8; CONJUGATE=9; ADHERE=10; SHARE=11
STEP_COST=1; EAT_RATE=6; DIVIDE_RESERVE=8; DIVIDE_COST=12; EDIT_COST=4; CONJUGATE_COST=3; ADHERE_COST=1; SHARE_AMOUNT=4; MAX_GENOME=48; MIN_GENOME=6
